project:
  type: book
  output-dir: ../docs

book:
  title: "DISPLACE California documentation"
  author: emLab, UCSB
  date: last-modified
  date-format: "[Last Updated on] MMMM DD, YYYY"
  chapters:
    - index.qmd
    - spatial_extend.qmd
    - populations.qmd
    - fisheries.qmd
    - routines.qmd
    - results.qmd
    # - references.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true          
    toc_depth: 5
execute:
  cache: true
editor: visual

